### PR TITLE
Change design layout of review.

### PR DESCRIPTION
**Pull request by JoshDunnDev**
Update of review step design layout. Text is now centered.

Screen Shot 2019-04-10 at 10 33 32 AM

### CODE REVIEW

**Comment by dlongley** [comment]
Hmm, I don't think that's what we want either. It seems like what we want is a centered area (with equal whitespace on the left and right) where that centered area is composed of two columns, such that the field names are in one column and the values are in the other.

**Comment by JoshDunnDev** [comment]
Initially I had a 2 column layout. It was 50% on left column (title) and 50% on right column (value). 

Here is an example of the previous 50% (text-right)/ 50% (text-left) layout. I added temporary borders to show width of areas.
Screen Shot 2019-04-10 at 2 54 11 PM

I have added this structure back and use 25% and 75% instead. This extra white space is variable with a 2 column layout because it depends how long the fields are.

Here is an example of the 25% / 75% layout. I added temporary borders to show width of areas. This layout has not text alignment specified.
Screen Shot 2019-04-10 at 2 40 19 PM

**Comment by dlongley** [comment]
@JoshDunnDev,

Pushed up something for you to look at that uses the flex column width and centering stuff (rather than hard-coding it to some number of grid columns, etc.) that I was trying to convey. There may still be issues if the field values are really long, so I imagine we need some more tweaks. Also, I noticed the review section titles weren't rendering, so I turned those on -- so we should look into making that look nicer as well.

**Comment by JoshDunnDev** [comment]
> Pushed up something for you to look at that uses the flex column width and centering stuff (rather than hard-coding it to some number of grid columns, etc.) that I was trying to convey. There may still be issues if the field values are really long, so I imagine we need some more tweaks. Also, I noticed the review section titles weren't rendering, so I turned those on -- so we should look into making that look nicer as well.

So it looks pretty good on desktop after these changes (I made a couple modifications):
Screen Shot 2019-04-10 at 10 23 42 PM

However with this new format, it completely breaks on mobile due to the grouped layout. Not sure how you want to solve this. We could have different HTML for mobile if that is the case or need to figure out a different layout that is more mobile friendly.

The field names and values are grouped in separate sections which does not allow for a stacking layout on mobile (Added temporary border to show groups):
Screen Shot 2019-04-10 at 10 31 00 PM

**Comment by dlongley** [comment]
@JoshDunnDev,

I think the underline might be a bit too busy, Maybe we could use a background color instead like a light gray... and use something built into quasar like a `q-banner` or `q-bar`?

Not sure what to do about mobile, but yeah, that's clearly a problem. I would recommend looking to see what other people have done to build responsive tables using flexbox.

**Comment by dlongley** [comment]
The other option we should explore (first) is just looking to see what quasar can do for us with displaying the data. There may be something that handles what we want right away (in both desktop/mobile cases).

**Comment by JoshDunnDev** [comment]
> The other option we should explore (first) is just looking to see what quasar can do for us with displaying the data. There may be something that handles what we want right away (in both desktop/mobile cases).

So I did a lot of research and can't seem to find a solution to make it the way you want and also make it work properly with mobile. 

I do have another design layout which might solve part of the problem. It would be using static column sizes but lay it out in a table format so it looks less like the text is off center.

Here is the desktop example:
Screen Shot 2019-04-11 at 12 46 26 PM

Here is the mobile example:
Screen Shot 2019-04-11 at 12 46 16 PM

**Comment by dlongley** [comment]
@JoshDunnDev,

I think the table layout looks ok. Let's make sure we're using components from quasar to do it though (as opposed to writing custom html and css). That should also help with ensuring it is more responsive without us having to test multiple screens. For example: [q-table](https://v1.quasar-framework.org/vue-components/table) or [q-markup-table](https://v1.quasar-framework.org/vue-components/markup-table).

**Comment by JoshDunnDev** [comment]
> @JoshDunnDev,
> 
> I think the table layout looks ok. Let's make sure we're using components from quasar to do it though (as opposed to writing custom html and css). That should also help with ensuring it is more responsive without us having to test multiple screens. For example: [q-table](https://v1.quasar-framework.org/vue-components/table) or [q-markup-table](https://v1.quasar-framework.org/vue-components/markup-table).

I am not using q-table because it's a very hard quasar component to work with. I am using q-card to do this. I did have to add a small amount of custom CSS for this. I will push my code so you can take a look.

**Review by dlongley — APPROVED** [review]

**Review by dlongley — APPROVED** [review]

**Pull request merged**
